# Generated by Django 3.0.6 on 2020-06-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20200603_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='is_started',
            new_name='email_required',
        ),
    ]
