# Generated by Django 3.0.6 on 2020-06-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20200606_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multi_choice',
            field=models.BooleanField(default=False),
        ),
    ]
